---
# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    # ADB
    androidtv.adb_manager: error

    # Deconz
    pydeconz: warn
    homeassistant.components.deconz: warn

    # Device tracker
    homeassistant.components.device_tracker.bluetooth_tracker: debug
    homeassistant.components.device_tracker.bluetooth_le_tracker: debug
    homeassistant.components.device_tracker: info

    # HA
    homeassistant.core: info
    homeassistant.setup: info

    # HACS
    custom_components.hacs: warn

    # Homekit
    homeassistant.components.homekit: info
    pyhap: info

    # Mediaplayer
    homeassistant.components.media_player: error

    # MQTT
    homeassistant.components.mqtt: info

    # Nabu Casa
    hass_nabucasa: warn
    snitun: warn

    # Waze
    homeassistant.components.waze_travel_time.sensor: error
