---
# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    # ADB
    androidtv.adb_manager: error

    # Deconz
    pydeconz: error
    homeassistant.components.deconz: error

    # Device tracker
    homeassistant.components.device_tracker.bluetooth_tracker: error
    homeassistant.components.device_tracker.bluetooth_le_tracker: error
    homeassistant.components.device_tracker: error

    # HA
    homeassistant.core: info
    homeassistant.setup: info
    homeassistant.components.stream.worker: debug
    # homeassistant.components.webhook: debug
    homeassistant.helpers.condition: warn
    homeassistant.components.androidtv.media_player: fatal
    homeassistant.companion.android: debug

    # HACS
    custom_components.hacs: warning

    # Homekit
    homeassistant.components.homekit: error
    pyhap: error

    # Mediaplayer
    homeassistant.components.media_player: error

    # MQTT
    homeassistant.components.mqtt: error

    # Nabu Casa
    hass_nabucasa: warn
    snitun: warn

    # Pychromecast
    pychromecast.socket_client: warn

    # Waze
    homeassistant.components.waze_travel_time.sensor: error
