---
#
logger:
  default: warning
  logs:
    pydeconz: warning
    homeassistant.components.deconz: warning
    custom_components.hacs: warning
    homeassistant.components.homekit: warning
    pyhap: warning
