---
#
netatmo:
  client_id: !secret netatmo_clientid
  client_secret: !secret netatmo_clientsecret
#  username: !secret netatmo_username
#  password: !secret netatmo_password
#  discovery: false
