---
######   https://www.home-assistant.io/components/person/   ######
person:
  - name: Allan Persson
    id: allanpersson
    device_trackers:
      - device_tracker.allanpersson_bt
      - device_tracker.allanpersson_forerunner_ble
      - device_tracker.allanpersson_forerunner_bt
      - device_tracker.allanpersson_nmap
      - device_tracker.sm_g965f
  - name: Caroline Hempel
    id: carolinehempel
    device_trackers:
      - device_tracker.carolinehempel_bt
      - device_tracker.carolinehempel_nmap
  - name: Ditte Hebsgaard
    id: dittehebsgaard
    device_trackers:
      - device_tracker.dittehebsgaard_nmap
  - name: Ea Hebsgaard
    id: eahebsgaard
    device_trackers:
      - device_tracker.eahebsgaard_bt
      - device_tracker.eahebsgaard_nmap
      - device_tracker.tecno_ca6
  - name: Emil Hempel
    id: emilhempel
    device_trackers:
      - device_tracker.emilhempel
      - device_tracker.emilhempel_bt
      - device_tracker.emilhempel_nmap
  - name: Irene Nissen
    id: irenenissen
    device_trackers:
      - device_tracker.irenenissen_bt
      - device_tracker.irenenissen_nmap
  - name: Otto
    id: otto
    device_trackers:
      - device_tracker.otto_ble
      - device_tracker.otto_bt
