---
# https://www.home-assistant.io/integrations/recorder/
recorder:
  # The number of days of history to keep in the recorder database
  purge_keep_days: 90

  # How often (in days) the purge task runs
  purge_interval: 1

  db_url: !secret recorder_db_url
