---
#
yeelight:
  devices:
    192.168.140.21:
      name: Soveværelset
      transition: 1000
      use_music_mode: true
      save_on_change: true
    192.168.140.20:
      name: Køkkenet Vask
      transition: 1000
      use_music_mode: true
      save_on_change: true
