---
garmin:
  name: "Garmin group"
  entities:
    - script.vacuum_return_to_dock
    - script.vacuum_start
    - script.vacuum_pause
    - script.cover_stuen_100_percent_open
    - script.cover_stuen_50_percent_open
    - script.cover_stuen_10_percent_open
    - script.cover_stuen_0_percent_open
    - script.godnat_vacuum_off
    - fan.badevaerelset
    - light.kokkenet_nilfisk
    - light.kokkenet_vask
    - light.baderum
    - light.badevaerelset
    - light.bornevaerelset
    - light.gangen
    - light.sovevaerelset
    - light.stuen_hvid
    - light.stuen_nilfisk
    - light.stuen_rod
    - light.stuen_sort
