---
#
garmin:
  view: true
  # control: hidden
  name: "Garmin group"
  # icon: mdi:lightbulb-on
  entities:
    - script.cover_stuen_100_percent_open
    - script.cover_stuen_50_percent_open
    - script.cover_stuen_10_percent_open
    - script.cover_stuen_0_percent_open
    - script.godnat_vacuum_off
    - light.kokkenet_nilfisk
    - light.kokkenet_vask
    - light.badevaerelset
    - light.bornevaerelset
    - light.gangen
    - light.sovevaerelset
    - light.stuen_hvid
    - light.stuen_nilfisk
    - light.stuen_rod
    - light.stuen_sort
