---
#
kokken_windows:
  name: "Køkken windows"
  icon: mdi:border-all-variant
  entities:
    - binary_sensor.window_kokkenet_lille
    - binary_sensor.window_kokkenet_hojre
    - binary_sensor.window_kokkenet_venstre
