---
#
person.alle:
  name: "Personer alle"
  icon: mdi:account-supervisor
  entities:
    - person.allan_persson
    - person.caroline_hempel
    - person.ditte_hebsgaard
    - person.ea_hebsgaard
    - person.emil_hempel
    - person.gaester
    - person.irene_nissen
