---
#
windows.alle:
  name: "Windows Alle"
  icon: mdi:border-all-variant
  entities:
    - binary_sensor.window_badevaerelset
    - binary_sensor.window_bornevaerelset
    - binary_sensor.window_kokkenet_hojre
    - binary_sensor.window_kokkenet_lille
    - binary_sensor.window_kokkenet_venstre
    - binary_sensor.window_stuen_hojre
    - binary_sensor.window_stuen_venstre
    - binary_sensor.door_altandor
    - binary_sensor.door_hoveddor
