---
#
alias: "[Notification] Plante: Ginseng"
id: 3cb5767f-f511-4287-aab9-6d45903b9533
trigger:
  - platform: time_pattern
    minutes: "/60"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.plante_stuen_ginseng_moisture
      below: 15
    - condition: state
      entity_id: person.allan_persson
      state: "home"
    - condition: time
      after: "10:00:00"
      before: "21:00:00"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Husk at vande!"
      message: >-
        Ginseng i stuen har brug for looooooove! Der er kun
        {{ states('sensor.plante_stuen_ginseng_moisture') }} % love tilbage...
      data:
        image: !secret ginseng_image
