---
#
godnat_vacuum_off:
  alias: "godnat vacuum off"
  sequence:
    - service: automation.turn_off
      entity_id: automation.autoclean_vacuum
    - delay: 09:00:00
    - service: automation.turn_on
      entity_id: automation.autoclean_vacuum
