---
#
vacuum_return_to_dock:
  alias: "Vacuum Return to dock"
  icon: mdi:home
  sequence:
    - service: vacuum.return_to_base
      entity_id: vacuum.james
    - delay:
        seconds: 5
    - service: vacuum.return_to_base
      entity_id: vacuum.james
