---
#
vacuum_bornevarelset:
  alias: "Vacuum Børneværelset"
  icon: mdi:baby
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.james
        command: app_zoned_clean
        params: [[26441, 23575, 29941, 26625, 2]]
