---
#
vacuum_stuen:
  alias: "Vacuum Stuen"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.james
        command: app_zoned_clean
        params: [[22214, 22354, 26364, 28154, 2]]
