---
#
vacuum_badevarelset:
  alias: "Vacuum Badeværelset"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.james
        command: app_zoned_clean
        params: [[27846, 20437, 29896, 23537, 2]]
