---
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
camera.dor:
  name: Kamera Hoveddør
  aliases:
    - Kamera Hoveddør
    - Camera Hoveddør
    - Kamera Dør
    - Camera Dør
    - Kamera Ude
    - Camera Ude
    - Kameraet Ude
  room: Ude
