---
#
alias: Cover update
trigger:
  - platform: time_pattern
    seconds: "/60"
# condition:
#   - condition: template
#     value_template: "{{ now().month > 9 }}" ## Starting September
#   - condition: template
#     value_template: "{{ now().month < 5 }}" ## Ending May
#   - condition: time
#     after: "07:00:00"
#     before: "22:00:00"
action:
  - service: homeassistant.update_entity
    entity_id: cover.stuen_hojre
  - service: homeassistant.update_entity
    entity_id: cover.stuen_venstre
