---
# https://www.home-assistant.io/integrations/waze_travel_time/
platform: waze_travel_time
name: 'Til Evigglad'
origin: person.allan_persson
destination: zone.evigglad
region: 'EU'
realtime: true
