---
# https://www.home-assistant.io/integrations/waze_travel_time/
platform: waze_travel_time
name: 'Til Hempel & Juhl'
origin: person.allan_persson
destination: zone.hempel_juhl
region: 'EU'
realtime: true
