---
# https://www.home-assistant.io/integrations/waze_travel_time/
platform: waze_travel_time
name: 'Til Anders Dall'
origin: person.allan_persson
destination: zone.anders_dall
region: 'EU'
realtime: true
