---
# https://www.home-assistant.io/integrations/waze_travel_time/
platform: waze_travel_time
name: "Til Mo's Friends"
origin: person.allan_persson
destination: zone.mo_s_friends
region: 'EU'
realtime: true
