---
# https://www.home-assistant.io/integrations/waze_travel_time/
platform: waze_travel_time
name: 'Til Ditte Hebsgaard'
origin: person.allan_persson
destination: zone.ditte_hebsgaard
region: 'EU'
realtime: true
