---
#
alias: "Lights on night (Gangen)"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_gang
    to: "on"
  - platform: state
    entity_id: binary_sensor.window_hoveddor
    to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_gang
      below: 10
    - condition: time
      after: "22:00"
      before: "07:00"
action:
  service: light.turn_on
  data:
    # transition: 1
    brightness_pct: 1
    rgb_color: [0, 0, 139]
    entity_id: light.gangen
