---
#
alias: "[Notification] Smokealarm"
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.fire_bornevaerelset
    to: "on"
  - platform: state
    entity_id: binary_sensor.fire_gangen
    to: "on"
  - platform: state
    entity_id: binary_sensor.fire_kokkenet
    to: "on"
  - platform: state
    entity_id: binary_sensor.fire_stuen
    to: "on"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Wake up!"
      message: "The house is on fire and the cat's stuck in the dryer!"
      data:
        image: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fedinburghfestivalguide.co.uk%2Fwp-content%2Fuploads%2F2015%2F01%2FBeltane-2010-by-Neil-Hodgins.jpg&f=1&nofb=1"
        ttl: 0
        priority: high
