---
#
alias: "Lights on day (Gangen)"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_gangen
    to: "on"
  - platform: state
    entity_id: binary_sensor.door_hoveddor
    to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_gangen
      below: 10
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      below: !secret sun_elevation_value
    - condition: state
      entity_id: light.gangen
      state: "off"
    - condition: time
      before: "22:00"
      after: "07:00"
action:
  service: light.turn_on
  data:
    # transition: 1
    brightness_pct: 100
    rgb_color: [240, 230, 140]
    entity_id: light.gangen
