---
#
alias: "Lights on night (Gangen)"
id: 33cc4b47-a960-4767-8149-47c4f9b7ff20
trigger:
  - platform: state
    entity_id: binary_sensor.motion_gangen
    to: "on"
  - platform: state
    entity_id: binary_sensor.door_hoveddor
    to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_gangen
      below: 10
    - condition: time
      after: "22:00"
      before: "07:00"
action:
  service: light.turn_on
  data:
    transition: 1
    brightness: 1
    rgb_color: [0, 0, 139]
    entity_id: light.gangen
