---
alias: "Stuen unavailable reboot"
id: 0465d71a-ca55-49df-a8b2-51f39b0255c3
trigger:
  - platform: state
    entity_id: media_player.stuen
    to: "unavailable"
    for: 00:03:00
  - platform: time_pattern
    minutes: "/5"
condition:
  - condition: state
    entity_id: sensor.android_tv_boks_state
    state: "on"
  - condition: state
    entity_id: media_player.stuen
    state: "unavailable"
action:
  - service: switch.turn_off
    entity_id: switch.google_home_stuen
  - delay:
      seconds: 30
  - service: switch.turn_on
    entity_id: switch.google_home_stuen
