---
#
alias: "Lights off (Soveværelset)"
id: 924dfba5-edc1-41a4-8c09-fee312041b8b
trigger:
  platform: state
  entity_id:
    - binary_sensor.motion_stuen
    - binary_sensor.huawei_mediapad_motion
  to: "off"
  for:
    minutes: 5
action:
  service: light.turn_off
  entity_id: light.sovevaerelset
