---
#
alias: "Notification (Postkasse)"
trigger:
  platform: state
  entity_id: binary_sensor.window_postkasse
  from: 'off'
  to: 'on'
action:
  - service: notify.join_allan
    data:
      title: "Post!"
      message: "Låget har været løftet, hvad mon du finder?"
