---
# https://www.home-assistant.io/integrations/light.mqtt/
platform: mqtt
name: "Baderum"
state_topic: "shellies/shelly1-B97644/relay/0"
command_topic: "shellies/shelly1-B97644/relay/0/command"
availability_topic: "shellies/shelly1-B97644/online"
qos: 0
payload_on: "on"
payload_off: "off"
payload_available: "true"
payload_not_available: "false"
optimistic: false
