---
#
alias: '[Notification] Vacuum: Docked'
id: 0f743d0a-d893-4f19-b1e6-c9530079b3f1
trigger:
  platform: state
  entity_id: vacuum.james
  to: "docked"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "James AFSLUTTET"
      message: >
        Han tager en velfortjent lur i docken efter at have rengjort
        {{ states('sensor.vacuum_cleaned_area') }} m2
        på {{ states('sensor.vacuum_cleaning_time') }} minutter.
        Vedligeholdelses status:
        {{ states('sensor.vacuum_cleanmainbrush') }}.
        {{ states('sensor.vacuum_cleansidebrush') }}.
        {{ states('sensor.vacuum_cleanfilter') }}.
        {{ states('sensor.vacuum_sensordirtyleft') }}.
      data:
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fd2otfaypcda2dg.cloudfront.net%2Fblog%2Fwp-content%2Fuploads%2F2018%2F10%2FRoborock-2-Vacuum-Cleaner-Review-charging-at-base-station.jpg&f=1&nofb=1"
