---
#
alias: "Lights on day (Køkkenet)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_kokken
  to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_kokken
      below: 20
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      below: !secret sun_elevation_value
    - condition: state
      entity_id: light.kokkenet_nilfisk
      state: "off"
    - condition: time
      after: "07:00"
      before: "22:00"
action:
  - service: light.turn_on
    entity_id: light.kokkenet_vask
    data:
      transition: 10
      brightness_pct: 70
      rgb_color: [255, 160, 39]
  - service: light.turn_on
    entity_id: light.kokkenet_nilfisk
    data:
      transition: 10
      brightness_pct: 70
      rgb_color: [255, 160, 39]
