---
# https://www.home-assistant.io/integrations/google_translate
platform: google_translate
# base_url: !secret google_translate_base_url

# Set the default voice language.
language: 'da'

# Cache voice files to a local storage.
cache: true

# Path to a location for caching the tts files.
cache_dir: /tmp/tts

# Time to hold (in seconds) the voice data inside memory for fast play
# on a media player. (min 60, max 57600)
time_memory: 300
