---
platform: min_max
name: "Pepehome Temperature (Last)"
type: "last"
round_digits: 2
entity_ids:
  - sensor.sovevaerelset_temperature
  - sensor.gangen_temperature
  - sensor.stuen_temperature
  - sensor.motion_stuen
  - sensor.kokkenet_temperature
  - sensor.bornevaerelset_temperature
  - sensor.badevaerelset_temperature
  - sensor.baderum_temperature
