---
#
platform: min_max
name: "Pepehome Temperature (Min)"
type: "min"
round_digits: 2
entity_ids:
  - sensor.sovevaerelset_temperature
  - sensor.gangen_temperature
  - sensor.stuen_temperature
  - sensor.motion_stuen_2
  - sensor.kokkenet_temperature
  - sensor.bornevaerelset_temperature
  - sensor.badevaerelset_temperature
