---
# ESPHome
ap_password: "password"
esp_bluetooth_board_ip: 192.168.0.1
esp_smartbell_ip: 192.168.0.1
miflora_mac: "aa:11:bb:22:cc:33"
xiaomi_temp_mac: "aa:11:bb:22:cc:33"
wifi_name: "wifiname"
wifi_secret: "wifipassword"
wifi_gateway: "192.168.0.1"
wifi_subnet: "255.255.255.255"
wifi_dns01: "8.8.8.8"
wifi_dns02: "1.1.1.1"
