---
# https://www.nabucasa.com/config/google_assistant
include_entities:
  #### Camera ####
  - camera.altan
  - camera.badevaerelset
  - camera.bornevaerelset
  - camera.dor
  - camera.gangen
  - camera.kokkenet
  - camera.stuen
  - camera.sovevaerelset

  #### Climate ####
  - climate.stuen

  #### Cover ####
  - cover.stuen_hojre
  - cover.stuen_venstre
  - script.cover_stuen_0_percent_open
  - script.cover_stuen_10_percent_open
  - script.cover_stuen_50_percent_open
  - script.cover_stuen_100_percent_open

  #### Device Trackers ####
  - device_tracker.eahebsgaard
  - device_tracker.mediapad
  - device_tracker.pepemobil

  #### Fans ####
  - fan.badevaerelset
  - fan.bornevaerelset

  #### Lights ####
  - light.baderum
  - light.badevaerelset
  - light.bornevaerelset
  - light.gangen
  - light.kokkenet_nilfisk
  - light.kokkenet_vask
  - light.sovevaerelset
  - light.stuen
  - light.stuen_nilfisk
  - light.stuen_sort
  - light.stuen_rod
  - light.stuen_hvid

  #### Media Players ####
  - media_player.android_tv_boks
  - media_player.android_tv_boks_lan
  - media_player.mibox4
  - media_player.kokkenet
  - media_player.samsung_tv
  - media_player.stuen

  #### Persons ####
  - person.allan_persson
  - person.ea_hebsgaard

  #### Sensors ####
  - binary_sensor.door_altandor
  - binary_sensor.door_hoveddor
  - binary_sensor.door_bornedor
  - binary_sensor.fire_stuen
  - sensor.owm_temperature
  - sensor.rejseplanen_engdalsvej_arhusvej_mod_aarhus_skanderborg
  - sensor.sovevaerelset

  #### Switches ####
  - switch.adguard_protection
  - switch.kokkenet
  - switch.ventilator_bornevaerelset
  - switch.google_home_stuen
  - switch.router

  #### Vacuum ####
  - vacuum.james
  - script.vacuum_return_to_dock
  - script.vacuum_start
  - script.vacuum_pause
  - script.vacuum_badevarelset
  - script.vacuum_bornevarelset
  - script.vacuum_gangen
  - script.vacuum_kokkenet
  - script.vacuum_stuen
