---
# https://github.com/gregoryduckworth/GoogleGeocode-HASS
platform: google_geocode
name: Google Geocode Pepemobil
origin: device_tracker.pepemobil
options: street, street_number, city
display_zone: hide
api_key: !secret google_maps_api
language: da-DK
region: DK
