---
#
alias: ha version update
trigger:
  - platform: time_pattern
    seconds: "/300"
# condition:
#   - condition: template
#     value_template: "{{ now().month > 9 }}" ## Starting September
#   - condition: template
#     value_template: "{{ now().month < 5 }}" ## Ending May
#   - condition: time
#     after: "07:00:00"
#     before: "22:00:00"
action:
  - service: homeassistant.update_entity
    entity_id: sensor.version_available
  - service: homeassistant.update_entity
    entity_id: sensor.version_beta
  - service: homeassistant.update_entity
    entity_id: sensor.version_current
