---
# https://www.home-assistant.io/integrations/person/
name: Caroline Hempel
id: carolinehempel
device_trackers:
  - device_tracker.carolinehempel
  - device_tracker.carolinehempel_bt
  - device_tracker.carolinehempel_unifi
