---
# https://www.home-assistant.io/integrations/person/
name: Ditte Hebsgaard
id: dittehebsgaard
device_trackers:
  - device_tracker.dittehebsgaard
  - device_tracker.dittehebsgaard_bt
  - device_tracker.dittehebsgaard_unifi
