---
# https://www.home-assistant.io/integrations/person/
name: Ea Hebsgaard
id: eahebsgaard
user_id: !secret user_id_person_ea
device_trackers:
  - device_tracker.eahebsgaard_bt
  - device_tracker.eahebsgaard_nmap
  - device_tracker.eahebsgaard
