---
# https://www.home-assistant.io/integrations/person/
name: Irene Nissen
id: irenenissen
device_trackers:
  - device_tracker.irenenissen
  - device_tracker.irenenissen_bt
  - device_tracker.irenenissen_unifi
