---
#
alias: "Notification (HA Upgrade)"
trigger:
  - platform: state
    entity_id: sensor.version_available
condition:
  - condition: template
    value_template: >
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: notify.join_allan
    data_template:
      title: Upgrade time!
      message: >
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      data:
        url: !secret nabucasa_url
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      notification_id: hassio_upgrade
