---
#
alias: "Router restart"
trigger:
  - platform: time
    at: "03:59:30"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.android_tv_boks
      state: "off"
    - condition: state
      entity_id: light.stuen
      state: "off"
action:
  - service: switch.turn_off
    entity_id: switch.router
  - delay:
      seconds: 30
  - service: switch.turn_on
    entity_id: switch.router
