---
# https://www.home-assistant.io/integrations/binary_sensor.template/
platform: template
sensors:
  pepemobil_charging:
    friendly_name: Pepemobil charging
    entity_id:
      - sensor.pepemobil_battery_level
    value_template: >
      {{ states.sensor.pepemobil_battery_level.attributes.is_charging }}
  mediapad_charging:
    friendly_name: Mediapad charging
    entity_id:
      - sensor.mediapad_battery_level
    value_template: >
      {{ states.sensor.mediapad_battery_level.attributes.is_charging }}
  eahebsgaard_charging:
    friendly_name: Eahebsgaard charging
    entity_id:
      - sensor.eahebsgaard_battery_level
    value_template: >
      {{ states.sensor.eahebsgaard_battery_level.attributes.is_charging }}
