---
#
alias: "[Notification] HA Upgrade"
id: d644b547-8a80-4ff1-81ce-1fa2f4520406
trigger:
  - platform: state
    entity_id: sensor.version_available
condition:
  - condition: template
    value_template: >
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: notify.mobile_app_pepemobil
    data_template:
      title: Upgrade time!
      message: >
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      data:
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.SHLpGBkErfffxdIk-q_aywHaGL%26pid%3DApi&f=1"
        clickAction: !secret ha_update_remote_url
        actions:
          - action: "URI"
            title: "Gå til supervisor (Lokal)"
            uri: !secret ha_update_local_url
          - action: "URI"
            title: "Gå til supervisor (Remote)"
            uri: !secret ha_update_remote_url
