---
#
alias: "HA version update"
id: 84db55b3-2547-4a68-a1bc-9bb1a85de7d7
trigger:
  - platform: time_pattern
    hours: "/6"
action:
  - service: homeassistant.update_entity
    entity_id: sensor.version_available
  - service: homeassistant.update_entity
    entity_id: sensor.version_beta
  - service: homeassistant.update_entity
    entity_id: sensor.version_current
