---
#
alias: "HA version update"
trigger:
  - platform: time_pattern
    hours: "/6"
action:
  - service: homeassistant.update_entity
    entity_id: sensor.version_available
  - service: homeassistant.update_entity
    entity_id: sensor.version_beta
  - service: homeassistant.update_entity
    entity_id: sensor.version_current
