---
alias: "Børneværelset switch"
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: bornevaerelset
      event: 1001
  - platform: event
    event_type: deconz_event
    event_data:
      id: bornevaerelset
      event: 1002
  - platform: event
    event_type: deconz_event
    event_data:
      id: bornevaerelset
      event: 2001
  - platform: event
    event_type: deconz_event
    event_data:
      id: bornevaerelset
      event: 2002
action:
  - service: light.turn_on
    entity_id: light.bornevaerelset
    data_template:
      hs_color:
        - "{{ (30 + (state_attr('light.bornevaerelset', 'hs_color')[0] or 0)) % 360 }}"
        - 100
      brightness_pct: 100
      transition: 15
