---
#
alias: "Lights off (Børneværelset)"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_bornevaerelset
    to: 'off'
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    above: !secret sun_elevation_value
action:
  - service: light.turn_off
    entity_id: light.bornevaerelset
