---
alias: "Fan Off (Børneværelset)"
id: a850566a-5469-4915-a0d3-f7ece5b464c4
trigger:
  - platform: numeric_state
    entity_id: sensor.bornevaerelset_temperature
    below: '23.0'
# condition:
#   condition: and
#   conditions:
#     - condition: numeric_state
#       entity_id: sensor.motion_stuen
#       below: 10
#     - condition: state
#       entity_id: media_player.android_tv_boks
#       state: 'playing'
#     - condition: state
#       entity_id: light.stuen
#       state: 'off'
action:
  service: switch.turn_off
  entity_id: switch.ventilator_bornevaerelset
