---
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
media_player.android_tv_boks:
  name: Android Tv Boks
  aliases:
    - Android Tv Boks
    - android tv
    - mi box
    - tv boks
  room: Stuen
