---
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
script.vacuum_badevarelset:
  name: Vacuum Badeværelset
  aliases:
    - Vacuum Badeværelset
    - Støvsug Badeværelset
    - Støvsugeren på Badeværelset
    - Støvsugeren i Badeværelset
    - Støvsugeren til Badeværelset
    - Støvsugning Badeværelset
    - Støvsugning på Badeværelset
    - Støvsugning i Badeværelset
    - Støvsugning til Badeværelset
    - Støvsug pølsehuset
  room: Badeværelset
