---
# Circadian Lighting slowly synchronizes your color changing lights with the
# regular naturally occuring color temperature of the sky throughout the day.
#
# This switch allows me to enable or disable this feature on the lights
# in our living room.
#
# https://github.com/claytonjn/hass-circadian_lighting
#
platform: circadian_lighting
name: stuen_circadian_lighting
lights_xy:
  - light.stuen_rod
  - light.stuen_sort
  - light.stuen_hvid
  - light.stuen_nilfisk
# lights_ct:
#   - light.living_room_television
