---
# https://shelly.cloud/
platform: mqtt
name: "Ventilator (Badeværelset)"
state_topic: "shellies/shelly1-B8EDDC/relay/0"
command_topic: "shellies/shelly1-B8EDDC/relay/0/command"
availability_topic: "shellies/shelly1-B8EDDC/online"
payload_on: "on"
payload_off: "off"
payload_available: "true"
payload_not_available: "false"
