---
#
alias: "[Automation] Pizero restart"
trigger:
  - platform: time_pattern
    hours: "/3"
action:
  - service: switch.turn_off
    entity_id: switch.kokkenet
  - delay:
      seconds: 15
  - service: switch.turn_on
    entity_id: switch.kokkenet
