---
#
alias: "[Automation] Router restart"
trigger:
  - platform: time
    at: "03:59:30"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.stuen
      state: "off"
    - condition: time
      weekday:
        - wed
        - sun
action:
  - service: switch.turn_off
    entity_id: switch.router
  - delay:
      seconds: 30
  - service: switch.turn_on
    entity_id: switch.router
