---
#
alias: "Dropbox Auto upload Snapshot"
trigger:
  - platform: time
    at: '02:00:00'
action:
  - service: hassio.addon_stdin
    data:
      addon: "7be23ff5_dropbox_sync"
      input: {"command":"upload"}
