---
#
alias: "Cover - Wake Up (Stuen)"
trigger:
  - platform: time_pattern
    seconds: "/60"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ (((as_timestamp(now()) | int) + 3*60) | timestamp_custom("%Y-%m-%d %H:%M:00")) == states.sensor.next_alarm.state }}'
    - condition: time
      after: "00:00:01"
      before: "11:59:59"
action:
  - service: script.cover_stuen_100_percent_open
