---
#
alias: "Cover - Kodi (Stuen)"
trigger:
  - platform: state
    entity_id: sensor.android_tv_boks_source
    to: "Kodi"
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: cover.stuen_hojre
      value_template: "{{ states.cover.stuen_hojre.attributes.current_position }}"
      above: 26
    - condition: numeric_state
      entity_id: cover.stuen_venstre
      value_template: "{{ states.cover.stuen_venstre.attributes.current_position }}"
      above: 26
action:
  - service: script.cover_stuen_0_percent_open
