---
#
alias: "Cover - Kodi (Stuen)"
trigger:
  - platform: state
    entity_id: media_player.kodi
    to: "paused"
  - platform: state
    entity_id: media_player.kodi
    to: "playing"
# condition:
#   condition: or
#   conditions:
#     - condition: state
#       entity_id: media_player.kodi
#       state: "idle"
#     - condition: state
#       entity_id: media_player.kodi
#       state: "off"
action:
  - service: script.cover_stuen_0_percent_open
