---
#
alias: "Lights off (Stuen)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_stuen
  to: "off"
  for:
    minutes: 30
action:
  service: light.turn_off
  data:
    transition: 60
    entity_id: light.stuen
