---
#
alias: "Lights on - Android Tv (Stuen)"
trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    below: !secret sun_elevation_value
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_stuen
      below: 10
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      below: !secret sun_elevation_value
    - condition: state
      entity_id: light.stuen
      state: "off"
    - condition: state
      entity_id: binary_sensor.window_altandor
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.android_tv_boks
          state: "paused"
        - condition: state
          entity_id: media_player.android_tv_boks
          state: "playing"
action:
  service: light.turn_on
  data:
    transition: 10
    brightness_pct: 10
    rgb_color: [255, 160, 39]
    entity_id: light.stuen
