---
#
alias: "Lights off (Stuen)"
trigger:
  - platform: state
    entity_id: binary_sensor.motion_stuen
    to: "off"
    for:
      minutes: 15
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    above: !secret sun_elevation_value
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: media_player.android_tv_boks
      state: "off"
    - condition: state
      entity_id: media_player.android_tv_boks
      state: "unavailable"
action:
  - service: light.turn_off
    data:
      transition: 10
      entity_id: light.stuen
