---
#
alias: "Autoclean (Vacuum)"
trigger:
  platform: time_pattern
  seconds: "/60"
condition:
  condition: and
  conditions:
    - condition: time
      after: "08:00:00"
      before: "21:00:00"
    - condition: template
      value_template: >
        {{as_timestamp(now()) - as_timestamp
        (states.vacuum.james.attributes.clean_stop) | int > 12600}}
    - condition: state
      entity_id: vacuum.james
      state: "docked"
    - condition: numeric_state
      entity_id: sensor.motion_born
      above: 5
action:
  - service: vacuum.start
    entity_id: vacuum.james
  - delay:
      milliseconds: 100
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.james
      fan_speed: 105
  - service: notify.join_allan
    data:
      title: "James er startet!"
      message: "Læn dig tilbage og lad ham gøre rent efter dig"
