---
platform: template
sensors:
  android_tv_boks_state:
    friendly_name: Android Tv Boks state
    entity_id:
      - media_player.samsung_tv
    value_template: >
      {% if states.media_player.samsung_tv.state == 'off'
      or states.media_player.samsung_tv.state == 'unavailable' %}
        off
      {% else %}
        on
      {% endif %}
    unit_of_measurement: ""
    icon_template: mdi:television
