---
platform: template
sensors:
  pepemobil_charging:
    friendly_name: Pepemobil charging
    entity_id:
      - sensor.pepemobil_battery_level
    value_template: >
      {{ states.sensor.pepemobil_battery_level.attributes.is_charging }}
    unit_of_measurement: ""
  pepemobil_charger_type:
    friendly_name: Pepemobil charger type
    entity_id:
      - sensor.pepemobil_battery_level
    value_template: >
      {{ states.sensor.pepemobil_battery_level.attributes.charger_type }}
    unit_of_measurement: ""
  mediapad_charging:
    friendly_name: Mediapad charging
    entity_id:
      - sensor.mediapad_battery_level
    value_template: >
      {{ states.sensor.mediapad_battery_level.attributes.is_charging }}
    unit_of_measurement: ""
  mediapad_charger_type:
    friendly_name: Mediapad charger type
    entity_id:
      - sensor.pepemobil_battery_level
    value_template: >
      {{ states.sensor.pepemobil_battery_level.attributes.charger_type }}
    unit_of_measurement: ""
  eahebsgaard_charging:
    friendly_name: Eahebsgaard charging
    entity_id:
      - sensor.eahebsgaard_battery_level
    value_template: >
      {{ states.sensor.eahebsgaard_battery_level.attributes.is_charging }}
    unit_of_measurement: ""
  eahebsgaard_charger_type:
    friendly_name: Eahebsgaard charger type
    entity_id:
      - sensor.eahebsgaard_battery_level
    value_template: >
      {{ states.sensor.eahebsgaard_battery_level.attributes.charger_type }}
    unit_of_measurement: ""
