---
platform: template
sensors:
  galaxys9plus_batterylevel:
    friendly_name: Galaxy S9plus battery
    entity_id:
      - device_tracker.pepemobil
    value_template: >
      {{ states.device_tracker.pepemobil.attributes.battery_level }}
    unit_of_measurement: "%"
    device_class: battery
  mediapad_batterylevel:
    friendly_name: Huawei Mediapad battery
    entity_id:
      - device_tracker.mediapad
    value_template: >
      {{ states.device_tracker.mediapad.attributes.battery_level }}
    unit_of_measurement: "%"
    device_class: battery
    icon_template: mdi:battery
  tecno_batterylevel:
    friendly_name: Tecno battery
    entity_id:
      - device_tracker.eahebsgaard
    value_template: >
      {{ states.device_tracker.eahebsgaard.attributes.battery_level }}
    unit_of_measurement: "%"
    device_class: battery
    icon_template: mdi:battery
  galaxys9plus_location:
    friendly_name: Galaxy S9plus location
    entity_id:
      - device_tracker.pepemobil
    value_template: >
      {{ states.device_tracker.pepemobil.attributes.latitude | float }},
      {{ states.device_tracker.pepemobil.attributes.longitude | float }}
    unit_of_measurement: ""
    icon_template: mdi:map-marker-plus
