---
platform: template
sensors:
  sun_elevation:
    friendly_name: Sun elevation
    entity_id:
      - sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    unit_of_measurement: "%"
