---
#
alias: "Cover - Sleep (Stuen)"
trigger:
  - platform: state
    entity_id: media_player.android_tv_boks
    to: "off"
condition:
  condition: and
  conditions:
    - condition: time
      after: "21:30:00"
      before: "07:00:00"
    - condition: numeric_state
      entity_id: cover.stuen_hojre
      value_template: "{{ states.cover.stuen_hojre.attributes.current_position }}"
      above: 26
    - condition: numeric_state
      entity_id: cover.stuen_venstre
      value_template: "{{ states.cover.stuen_venstre.attributes.current_position }}"
      above: 26
action:
  - service: cover.set_cover_position
    entity_id: cover.stuen_venstre
    data:
      position: 23
  - delay:
      milliseconds: 100
  - service: cover.set_cover_position
    entity_id: cover.stuen_hojre
    data:
      position: 23
