---
#
alias: "Lights off (Badeværelset)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_bad
  to: 'off'
  for:
    minutes: 1
action:
  service: light.turn_off
  entity_id: light.badevaerelset
