---
#
alias: "Lights on - Android Tv (Stuen)"
id: d4400beb-3185-4a47-8b82-4308d610c18b
trigger:
  - platform: time_pattern
    seconds: "/180"
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    below: !secret sun_elevation_value
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_stuen_2
      below: 10
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      below: !secret sun_elevation_value
    - condition: state
      entity_id: light.stuen
      state: "off"
    - condition: state
      entity_id: binary_sensor.door_altandor
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.samsung_tv
          state: "on"
        - condition: state
          entity_id: media_player.android_tv_boks
          state: "paused"
        - condition: state
          entity_id: media_player.android_tv_boks
          state: "playing"
        - condition: state
          entity_id: sensor.android_tv_boks_state
          state: "on"
action:
  - service: light.turn_on
    data:
      transition: 10
      brightness: 40
      rgb_color: [139, 69, 19]
      entity_id: light.stuen_nilfisk
  - service: light.turn_on
    data:
      transition: 10
      brightness: 50
      rgb_color: [255, 160, 39]
      entity_id: light.stuen_hvid
  - service: light.turn_on
    data:
      transition: 10
      brightness: 70
      rgb_color: [85, 107, 47]
      entity_id: light.stuen_sort
  - service: light.turn_on
    data:
      transition: 10
      brightness: 60
      rgb_color: [255, 69, 0]
      entity_id: light.stuen_rod
