---
alias: "Lights off - Android Tv (Stuen)"
trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: state
    entity_id: sensor.android_tv_boks_state
    to: "off"
condition:
  condition: and
  conditions:
    - condition: time
      after: "22:00:00"
      before: "07:00:00"
    - condition: state
      entity_id: sensor.android_tv_boks_state
      state: "off"
    - condition: state
      entity_id: light.stuen
      state: "on"
    - condition: state
      entity_id: binary_sensor.motion_stuen
      state: "off"
      for:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.motion_badevaerelset
      state: "off"
      for:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.motion_kokkenet
      state: "off"
      for:
        minutes: 5
action:
  - service: light.turn_off
    entity_id: light.stuen
