---
#
alias: "Lights off (Stuen)"
id: ce0dcfed-861a-4195-b2a5-6b3af09b2fd5
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ states.sun.sun.attributes.elevation }}"
    above: !secret sun_elevation_value
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      above: !secret sun_elevation_value
action:
  - service: light.turn_off
    data:
      transition: 10
      entity_id: light.stuen
