---
# https://hacs.xyz/docs/basic/automation
alias: "[Notification] HACS Update"
id: aef25931-baab-441a-8846-b774bb4494d7
trigger:
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
  - condition: template
    value_template: "{{ (states(trigger.entity_id) | float) != 0}}"
action:
  - service: notify.mobile_app_pepemobil
    data_template:
      title: Updates pending in HACS
      message: >-
        {% for repo in state_attr(trigger.entity_id, 'repositories') %}
          {{ repo.display_name }} _{{ repo["installed version"] }}_ -> _{{ repo["available version"] }}_
        {% endfor %}
      data:
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.SHLpGBkErfffxdIk-q_aywHaGL%26pid%3DApi&f=1"
        clickAction: /hacs
        actions:
          - action: URI
            uri: /hacs
            title: "Gå til HACS"
