---
#
alias: "Climate auto home"
trigger:
  - platform: state
    entity_id: group.person_alle
    to: "home"
  - platform: time_pattern
    seconds: "/300"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.owm_temperature
      below: "17.0"
    - condition: state
      entity_id: group.person_alle
      state: "home"
    - condition: time
      after: "06:00:00"
      before: "22:00:00"
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.stuen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.stuen
      target_temp_high: 22.1
      temperature: 22.0
      target_temp_low: 21.0
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.gangen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.gangen
      target_temp_high: 22.1
      temperature: 22.0
      target_temp_low: 21.0
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kokkenet
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.kokkenet
      target_temp_high: 22.1
      temperature: 22.0
      target_temp_low: 21.0
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.badevaerelset
      target_temp_high: 22.1
      temperature: 22.0
      target_temp_low: 21.0
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bornevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.bornevaerelset
      target_temp_high: 22.1
      temperature: 22.0
      target_temp_low: 21.0
      hvac_mode: "heat"
