---
#
alias: "[Notification] Altandør"
id: a8f1673e-2e10-48ab-8bfd-f3b821ba4f3a
trigger:
  platform: state
  entity_id: binary_sensor.door_altandor
  from: "off"
  to: "on"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Altandør!"
      message: "Døren er netop blevet åbnet...."
      data:
        image: !secret altan_image
