---
#
alias: "[Notification] Børnedør"
id: 57693285-5d82-46fa-b9ba-6f6703b01bb1
trigger:
  - platform: state
    entity_id: binary_sensor.door_bornedor
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: person.ea_hebsgaard
      state: "home"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Børnedør!"
      message: "Døren er netop blevet åbnet...."
      data:
        image: /api/camera_proxy/camera.bornevaerelset
        clickAction: /api/camera_proxy/camera.bornevaerelset
        color: red
        ttl: 0
        priority: high
        actions:
          - action: URI
            uri: /lovelace/pepehome
            title: "Pepehome"
          - action: URI
            uri: /lovelace/personer
            title: "Personer"
          - action: URI
            uri: /lovelace/lamper
            title: "Lamper"
