---
#
alias: "[Notification] Børnedør"
trigger:
  platform: state
  entity_id: binary_sensor.door_bornedor
  from: 'off'
  to: 'on'
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Børnedør!"
      message: "Døren er netop blevet åbnet...."
