---
#
alias: "[Notification] Hoveddør"
trigger:
  platform: state
  entity_id: binary_sensor.door_hoveddor
  from: "off"
  to: "on"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "Hoveddør!"
      message: "Døren er netop blevet åbnet...."
      data:
        ttl: 0
        priority: high
