---
# https://www.home-assistant.io/integrations/fan.mqtt/
platform: mqtt
name: "Badeværelset"
state_topic: "shellies/shelly1-B8EDDC/relay/0"
command_topic: "shellies/shelly1-B8EDDC/relay/0/command"
availability_topic: "shellies/shelly1-B8EDDC/online"
qos: 0
payload_on: "on"
payload_off: "off"
payload_available: "true"
payload_not_available: "false"
payload_high_speed: "on"
speeds:
  - "off"
  - high
