---
#
platform: template
fans:
  badevaerelset:
    friendly_name: "Badeværelset"
    value_template: "{{ states('switch.ventilator_badevaerelset') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.ventilator_badevaerelset
    turn_off:
      service: switch.turn_off
      entity_id: switch.ventilator_badevaerelset
