---
#
platform: template
fans:
  bornevaerelset:
    friendly_name: "Børneværelset"
    value_template: "{{ states('switch.ventilator_bornevaerelset') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.ventilator_bornevaerelset
    turn_off:
      service: switch.turn_off
      entity_id: switch.ventilator_bornevaerelset
