---
alias: "Børneværelset unavailable reboot"
trigger:
  - platform: state
    entity_id: media_player.bornevaerelset
    to: "unavailable"
    for:
      minutes: 1
action:
  - service: rest_command.gh_born_reboot
