---
alias: "Køkkenet unavailable reboot"
trigger:
  - platform: state
    entity_id: media_player.kokkenet
    to: "unavailable"
    for:
      minutes: 1
action:
  - service: rest_command.gh_kokken_reboot
