---
#
alias: "Google Home badeværelset volume sync"
id: 84feb1e6-7fa1-40c3-8af4-46a1b1e5c254
trigger:
  - platform: state
    entity_id: media_player.badevaerelset
condition:
  - condition: template
    value_template: >
      {% set from = trigger.from_state.attributes.volume_level | float %}
      {% set to = trigger.to_state.attributes.volume_level | float %}
      {{ to != from }}
  - condition: state
    entity_id: person.gaester
    state: "not_home"
action:
  - delay:
      milliseconds: 50
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.gangen
      volume_level: >
        {{states.media_player.badevaerelset.
        attributes.volume_level }}
  - delay:
      milliseconds: 50
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kokkenet
      volume_level: >
        {{states.media_player.badevaerelset.
        attributes.volume_level }}
  - delay:
      milliseconds: 50
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.stuen
      volume_level: >
        {{states.media_player.badevaerelset.
        attributes.volume_level }}
