---
#
alias: "[Notification] Allanpersson.dk down"
trigger:
  - platform: state
    entity_id: binary_sensor.allanpersson_dk
    from: "on"
    to: "off"
action:
  - service: notify.mobile_app_pepemobil
    data_template:
      title: Allanpersson.dk is down!
      message: >
        Be aware of downtime on allanpersson.dk!
