---
#
alias: "[Notification] Mosfriends.dk down"
id: a2dd8161-08eb-49e7-8584-cb07d9626a59
trigger:
  - platform: state
    entity_id: binary_sensor.mosfriends_dk
    from: "on"
    to: "off"
action:
  - service: notify.mobile_app_pepemobil
    data_template:
      title: Mosfriends.dk is down!
      message: >
        Be aware of downtime on mosfriends.dk!
      data:
        image: !secret uptimerobot_image
