---
#
alias: "Notification (Mosfriends.dk down)"
trigger:
  - platform: state
    entity_id: binary_sensor.mosfriends_dk
    from: "on"
    to: "off"
action:
  - service: notify.mobile_app_sm_g965f
    data_template:
      title: Mosfriends.dk is down!
      message: >
        Be aware of downtime on mosfriends.dk!
