---
#
alias: "Notification (Salomonisk.dk down)"
trigger:
  - platform: state
    entity_id: binary_sensor.salomonisk_dk
    from: "on"
    to: "off"
action:
  - service: notify.mobile_app_sm_g965f
    data_template:
      title: Salomonisk.dk is down!
      message: >
        Be aware of downtime on salomonisk.dk!
