---
#
alias: "Lights off (Børneværelset)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_born
  to: 'off'
  for:
    minutes: 15
action:
  service: light.turn_off
  entity_id: light.bornevaerelset
