---
alias: "Test Ikea switch"
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: huset
      event: 1001
  - platform: event
    event_type: deconz_event
    event_data:
      id: huset
      event: 1002
  - platform: event
    event_type: deconz_event
    event_data:
      id: huset
      event: 2001
  - platform: event
    event_type: deconz_event
    event_data:
      id: huset
      event: 2002
# condition:
#   - condition: template
#     value_template: >
#        {% set x = trigger.event.data.event|string %}
#        {{ x|length != 4 or x[1:3] != '00' }}
action:
  - service: light.turn_on
    # data_template:
    # transition: 1
    # brightness_pct: >
    #    {{states.light.stuen_nilfisk.attributes.brightness + 10}}'
    # rgb_color: [255 , 160 , 39]
    entity_id: light.bornevaerelset
  - service: switch.turn_on
    entity_id: switch.born
  - delay:
      seconds: 100
  - service: switch.turn_off
    entity_id: switch.born
  - service: light.turn_off
    # data_template:
    # transition: 1
    # brightness_pct: >
    #     '{{states.light.stuen_nilfisk.attributes.brightness + 10}}'
    # rgb_color: [255 , 160 , 39]
    entity_id: light.bornevaerelset
