---
#
alias: "[Climate] auto away"
id: 79ed4b01-a209-4649-af68-b1181d6209b4
trigger:
  - platform: state
    entity_id: group.person_alle
    to: "not_home"
  - platform: time_pattern
    seconds: "/300"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.owm_temperature
      below: 17
    - condition: state
      entity_id: group.person_alle
      state: "not_home"
    - condition: time
      after: !secret climate_day_start
      before: !secret climate_night_start
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.stuen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.stuen
      target_temp_high: !secret away_target_temp_high
      temperature: !secret away_target_temp
      target_temp_low: !secret away_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.gangen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.gangen
      target_temp_high: !secret away_target_temp_high
      temperature: !secret away_target_temp
      target_temp_low: !secret away_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kokkenet
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.kokkenet
      target_temp_high: !secret away_target_temp_high
      temperature: !secret away_target_temp
      target_temp_low: !secret away_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.badevaerelset
      target_temp_high: !secret away_target_temp_high
      temperature: !secret away_target_temp
      target_temp_low: !secret away_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bornevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.bornevaerelset
      target_temp_high: !secret away_target_temp_high
      temperature: !secret away_target_temp
      target_temp_low: !secret away_target_temp_low
      hvac_mode: "heat"
