---
#
alias: "[Climate] close windows"
id: c49a5a95-fd0b-49ec-873c-e8a1848f750b
trigger:
  - platform: state
    entity_id: group.windows_alle
    to: "off"
    for: 00:00:20
action:
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_away
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_home
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_sleep
