---
#
alias: "[Climate] close windows"
trigger:
  - platform: state
    entity_id: group.windows_alle
    to: "off"
    for:
      seconds: 20
action:
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_away
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_home
  - service: automation.turn_on
    data:
      entity_id: automation.climate_auto_sleep
