---
#
alias: "[Climate] naked on"
id: 1e5905b8-367e-4527-b186-0bd179449266
trigger:
  - platform: state
    entity_id: input_boolean.naked_mode
    to: "on"
action:
  - service: automation.turn_off
    data:
      entity_id: automation.climate_auto_away
  - service: automation.turn_off
    data:
      entity_id: automation.climate_auto_home
  - service: automation.turn_off
    data:
      entity_id: automation.climate_auto_off
  - service: automation.turn_off
    data:
      entity_id: automation.climate_close_windows
  - service: automation.turn_off
    data:
      entity_id: automation.climate_open_windows
  - service: automation.turn_off
    data:
      entity_id: automation.climate_auto_sleep
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.stuen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.stuen
      target_temp_high: !secret naked_target_temp_high
      temperature: !secret naked_target_temp
      target_temp_low: !secret naked_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.gangen
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.gangen
      target_temp_high: !secret naked_target_temp_high
      temperature: !secret naked_target_temp
      target_temp_low: !secret naked_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kokkenet
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.kokkenet
      target_temp_high: !secret naked_target_temp_high
      temperature: !secret naked_target_temp
      target_temp_low: !secret naked_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.badevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.badevaerelset
      target_temp_high: !secret naked_target_temp_high
      temperature: !secret naked_target_temp
      target_temp_low: !secret naked_target_temp_low
      hvac_mode: "heat"
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bornevaerelset
      hvac_mode: "heat"
  - service: climate.set_temperature
    data:
      entity_id: climate.bornevaerelset
      target_temp_high: !secret naked_target_temp_high
      temperature: !secret naked_target_temp
      target_temp_low: !secret naked_target_temp_low
      hvac_mode: "heat"
