---
#
alias: "Leaving home turn off"
id: a6530e65-17e4-4953-b729-eecb288436a6
trigger:
  - platform: state
    entity_id: group.person_alle
    to: "not_home"
    for:
      minutes: 15
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.light_alle
      state: "on"
    - condition: state
      entity_id: media_player.samsung_tv
      state: "playing"
    - condition: state
      entity_id: media_player.samsung_tv
      state: "paused"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "1 minut til auto sluk"
      message: >
        {{ "PepeHome slukker automatisk om 1 minut,
        da der ikke er registreret nogen hjemme i 30 minutter"}}
  - delay:
      minutes: 1
  - service: light.turn_off
    entity_id: group.light_alle
  - service: media_player.turn_off
    entity_id: media_player.samsung_tv
