---
#
alias: "Magic cube volume"
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
condition:
  - condition: template
    value_template: >
       {% set x = trigger.event.data.event|string %}
       {{ x|length != 4 or x[1:3] != '00' }}
action:
  - service: media_player.volume_set
    entity_id: media_player.stuen
    data_template:
      volume_level: >
         {% if trigger.event.data.event | float > 0 %}
           {{ states.media_player.stuen.
           attributes.volume_level + 0.01 }}
         {% else %}
           {{ states.media_player.stuen.
           attributes.volume_level - 0.01 }}
         {% endif %}
    # - service: media_player.volume_set
    #   entity_id: media_player.android_tv_boks
    #   data_template:
    #      volume_level: >
    #        {% if trigger.event.data.event | float > 0 %}
    #          {{ states.media_player.android_tv_boks.
    #          attributes.volume_level + 0.01 }}
    #        {% else %}
    #          {{ states.media_player.android_tv_boks.
    #          attributes.volume_level - 0.01 }}
    #        {% endif %}
