---
#
alias: "Openuv update"
id: 070d8871-4361-468c-b69c-600698345c9b
trigger:
  platform: time_pattern
  minutes: "/60"
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
action:
  service: openuv.update_data
