---
esphome:
  name: bluetooth
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_secret
  fast_connect: true
  reboot_timeout: 60min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth Fallback Hotspot"
    password: !secret ap_password

esp32_ble_tracker:

captive_portal:

# Enable logging.
logger:

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Bluetooth ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Bluetooth IP
    ssid:
      name: Bluetooth SSID
    bssid:
      name: Bluetooth BSSID

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora_mac
    temperature:
      name: "plante_stuen_ginseng_temperature"
    moisture:
      name: "plante_stuen_ginseng_moisture"
    illuminance:
      name: "plante_stuen_ginseng_light_intensity"
    conductivity:
      name: "plante_stuen_ginseng_conductivity"
    battery_level:
      name: "plante_stuen_ginseng_battery"

  - platform: xiaomi_lywsdcgq
    mac_address: !secret xiaomi_temp_mac
    temperature:
      name: "Gangen_display_temperature"
    humidity:
      name: "Gangen_display_humidity"
    battery_level:
      name: "Gangen_display_battery"

  - platform: wifi_signal
    name: "Bluetooth board WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor

binary_sensor:
  - platform: status
    name: "Bluetooth board Status"

  - platform: ble_presence
    mac_address: !secret pepemobil_mac
    name: "ESP32 BLE Pepemobil"
