---
#
alias: "Start on startup"
trigger:
  - platform: homeassistant
    event: start
action:
  - service: switch.turn_on
    entity_id: switch.google_home_stuen
  - service: switch.turn_on
    entity_id: switch.kokkenet
  - service: switch.turn_on
    entity_id: switch.router
