---
# https://www.home-assistant.io/integrations/miflora
platform: miflora
mac: !secret miflora_mac_ginseng
name: Plante (Stuen, Ginseng)
force_update: false
median: 3
monitored_conditions:
  - moisture
  - light
  - temperature
  - conductivity
  - battery
