---
platform: systemmonitor
resources:
  - type: disk_use_percent
    arg: /
  - type: disk_use
    arg: /
  - type: disk_free
    arg: /
  - type: memory_use_percent
  - type: memory_free
  - type: memory_use
  - type: swap_use_percent
  - type: swap_use
  - type: swap_free
  - type: load_1m
  - type: load_5m
  - type: load_15m
  - type: network_in
    arg: 'eno1'
  - type: network_out
    arg: 'eno1'
  - type: throughput_network_in
    arg: 'eno1'
  - type: throughput_network_out
    arg: 'eno1'
  - type: packets_in
    arg: 'eno1'
  - type: packets_out
    arg: 'eno1'
  - type: ipv4_address
    arg: 'eno1'
  - type: ipv6_address
    arg: 'eno1'
  - type: processor_use
  - type: process
  - type: last_boot
