---
# https://www.home-assistant.io/integrations/mitemp_bt/
platform: mitemp_bt
# mac: !secret xiaomi_temp_mac_baderum
# name: Gangen display
# force_update: true
# median: 1
# timeout: 60
# retries: 10
# cache_value: 300
# monitored_conditions:
#   - temperature
#   - humidity
#   - battery
