---
# Set the default theme on start up of Home Assistant.
#
# This, of course, only affects machine that do not
# have a theme set.
#
alias: "Default HA Theme"
id: 68bad14f-07bc-4bc5-8aed-90e50ed7e746
initial_state: true
trigger:
  platform: homeassistant
  event: start
action:
  service: frontend.set_theme
  data:
    name: Google Dark Theme
