---
#
alias: "Ventilator on (Badeværelset)"
id: 2fbe3aa9-d29a-421d-b0ae-1eb7fff784f7
trigger:
  - platform: numeric_state
    entity_id: sensor.baderum_humidity
    above: "60"
  - platform: numeric_state
    entity_id: sensor.badevaerelset_humidity
    above: "60"
  - platform: numeric_state
    entity_id: sensor.gangen_humidity
    above: "60"
  - platform: numeric_state
    entity_id: sensor.kokkenet_humidity
    above: "60"
  - platform: numeric_state
    entity_id: sensor.stuen_humidity
    above: "60"
action:
  - service: fan.turn_on
    entity_id: fan.badevaerelset
