---
#
alias: "Guest mode (Badeværelset)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_badevaerelset
  to: "on"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: person.gaester
      state: "home"
    - condition: time
      after: "07:00"
      before: "23:30"
    - condition: state
      entity_id: media_player.badevaerelset
      state: "off"
action:
  - service: media_player.turn_on
    entity_id: media_player.badevaerelset
  - delay:
      milliseconds: 100
  - service: media_player.play_media
    data_template:
      entity_id: media_player.badevaerelset
      media_content_id: http://live-icy.gss.dr.dk/A/A21H.mp3
      media_content_type: "music"
  - delay:
      milliseconds: 100
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.badevaerelset
      volume_level: 0.20
  - delay:
      minutes: 7
  - service: media_player.turn_off
    entity_id: media_player.badevaerelset
