---
#
alias: "Lights on day (Badeværelset)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_badevaerelset
  to: "on"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_badevaerelset
      below: 50
    - condition: time
      before: "22:30"
      after: "07:00"
action:
  service: light.turn_on
  data:
    transition: 1
    brightness_pct: 100
    rgb_color: [255, 255, 255]
    entity_id: light.badevaerelset
