---
#
alias: "Ventilator off (Badeværelset)"
id: 1efa0c0f-14f3-4533-b6c6-e7d983091e3c
trigger:
  - platform: numeric_state
    entity_id: sensor.baderum_humidity
    below: "60"
  - platform: numeric_state
    entity_id: sensor.badevaerelset_humidity
    below: "60"
  - platform: numeric_state
    entity_id: sensor.gangen_humidity
    below: "60"
  - platform: numeric_state
    entity_id: sensor.kokkenet_humidity
    below: "60"
  - platform: numeric_state
    entity_id: sensor.stuen_humidity
    below: "60"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.baderum_humidity
      below: "60"
    - condition: numeric_state
      entity_id: sensor.badevaerelset_humidity
      below: "60"
    - condition: numeric_state
      entity_id: sensor.gangen_humidity
      below: "60"
    - condition: numeric_state
      entity_id: sensor.kokkenet_humidity
      below: "60"
    - condition: numeric_state
      entity_id: sensor.stuen_humidity
      below: "60"
action:
  - service: fan.turn_off
    entity_id: fan.badevaerelset
