---
#
alias: "Lights on night (Badeværelset)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_badevaerelset
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.motion_badevaerelset
      below: 50
    - condition: time
      after: '22:30'
      before: '07:00'
action:
  - service: light.turn_on
    entity_id: light.badevaerelset
    data:
      transition: 1
      brightness_pct: 1
      rgb_color: [255, 160, 39]
