---
#
alias: "Notification (Altandør)"
trigger:
  platform: state
  entity_id: binary_sensor.window_altandor
  from: "off"
  to: "on"
action:
  - service: notify.mobile_app_sm_g965f
    data:
      title: "Altandør!"
      message: "Døren er netop blevet åbnet...."
