---
#
alias: "Notification (Børnedør)"
trigger:
  platform: state
  entity_id: binary_sensor.window_bornedor
  from: 'off'
  to: 'on'
action:
  - service: notify.mobile_app_sm_g965f
    data:
      title: "Børnedør!"
      message: "Døren er netop blevet åbnet...."
