---
# https://hacs.xyz/docs/basic/automation
alias: "Notification (HACS Update)"
trigger:
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
  - condition: template
    value_template: "{{ (states(trigger.entity_id) | float) != 0}}"
action:
  # - service: persistent_notification.create
  #   data_template:
  #     title: Updates pending in HACS
  #     message: >-
  #       {% for repo in state_attr(trigger.entity_id, 'repositories') %}
  #         **{{ repo.display_name }}** _{{ repo["installed version"] }}_ -> _{{ repo["available version"] }}_
  #       {% endfor %}
  - service: notify.join_allan
    data_template:
      title: Updates pending in HACS
      message: >-
        {% for repo in state_attr(trigger.entity_id, 'repositories') %}
          {{ repo.display_name }} _{{ repo["installed version"] }}_ -> _{{ repo["available version"] }}_
        {% endfor %}
