---
#
alias: "Notification (Hoveddør)"
trigger:
  platform: state
  entity_id: binary_sensor.window_hoveddor
  from: "off"
  to: "on"
action:
  - service: notify.mobile_app_sm_g965f
    data:
      title: "Hoveddør!"
      message: "Døren er netop blevet åbnet...."
