---
#
alias: "Plante: Ginseng, Stuen"
trigger:
  - platform: time_pattern
    minutes: "/60"
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sensor.plante_stuen_ginseng_moisture
      below: 10
    - condition: state
      entity_id: person.allan_persson
      state: "home"
    - condition: time
      after: "10:00:00"
      before: "21:00:00"
action:
  - service: notify.mobile_app_sm_g965f
    data:
      title: "Husk at vande!"
      message: "Ginseng i stuen har brug for looooooove"
