---
#
alias: "Smokealarm (Notification)"
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.lumi_sensor_smoke
    to: "on"
  - platform: state
    entity_id: binary_sensor.lumi_sensor_smoke_2
    to: "on"
  - platform: state
    entity_id: binary_sensor.lumi_sensor_smoke_3
    to: "on"
  - platform: state
    entity_id: binary_sensor.lumi_sensor_smoke_4
    to: "on"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "SOS! Røgalarm aktiveret"
      message: "Red alle mennesker ud!"
