---
#
alias: "Vacuum docked (Notification)"
trigger:
  platform: state
  entity_id: vacuum.james
  to: "docked"
action:
  - service: notify.mobile_app_pepemobil
    data:
      title: "James AFSLUTTET"
      message: >
        "Han tager en velfortjent lur i docken efter at have rengjort {{ states('sensor.vacuum_cleaned_area') }} m2
         på {{ states('sensor.vacuum_cleaning_time') }} minutter.
         Vedligeholdelses status:
        {{ states('sensor.vacuum_cleanmainbrush') }}.
        {{ states('sensor.vacuum_cleansidebrush') }}.
        {{ states('sensor.vacuum_cleanfilter') }}.
        {{ states('sensor.vacuum_sensordirtyleft') }}."
