---
#
alias: "Lights off day (Køkkenet)"
trigger:
  platform: state
  entity_id: binary_sensor.motion_kokken
  to: 'off'
  for:
    minutes: 5
condition:
  condition: and
  conditions:
    - condition: time
      before: '22:00'
      after: '07:00'
action:
  service: light.turn_off
  entity_id:
    - light.kokkenet_nilfisk
    - light.kokkenet_vask
