---
# https://www.home-assistant.io/integrations/history_stats/
platform: history_stats
name: Android tv Yousee ratio (today)
entity_id: sensor.android_tv_boks_source
state: "youSee"
type: ratio
start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
end: "{{ now() }}"
