---
# https://www.home-assistant.io/integrations/history_stats/
platform: history_stats
name: Allan Persson ratio away (today)
entity_id: device_tracker.allanpersson
state: "not_home"
type: ratio
start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
end: "{{ now() }}"
