---
#
# Dark Mint Theme
#
dark_mint:
  accent-color: "#BA5E49"
  card-background-color: "var(--primary-background-color)"
  dark-primary-color: "var(--accent-color)"
  disabled-text-color: "#7F848E"
  divider-color: "rgba(0, 0, 0, .12)"
  google-blue-500: "#4285f4"
  google-green-500: "#39E949"
  google-red-500: "#E45E65"
  google-yellow-500: "#f4b400"
  ha-card-border-radius: "6px"
  label-badge-background-color: "#2E333A"
  label-badge-blue: "#039be5"
  label-badge-border-color: "green"
  label-badge-green: "#0DA035"
  label-badge-grey: "var(--paper-grey-500)"
  label-badge-red: "var(--accent-color)"
  label-badge-text-color: "var(--primary-text-color)"
  label-badge-yellow: "#47D17A"
  light-primary-color: "var(--accent-color)"
  paper-card-background-color: "#3D3D3D"
  paper-card-header-color: "var(--accent-color)"
  paper-dialog-background-color: "#525252"
  paper-grey-200: "#414A59"
  paper-grey-50: "var(--primary-text-color)"
  paper-grey-500: "#9e9e9e"
  paper-item-icon-active-color: "#47D17A"
  paper-item-icon-color: "var(--primary-text-color)"
  paper-item-icon_-_color: "green"
  paper-item-selected_-_background-color: "#4A4346"
  paper-listbox-background-color: "#292929"
  paper-listbox-color: "var(--primary-color)"
  paper-slider-active-color: "var(--accent-color)"
  paper-slider-container-color: "linear-gradient(var(--primary-background-color) var(--secondary-background-color)) no-repeat"
  paper-slider-disabled-active-color: "var(--disabled-text-color)"
  paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
  paper-slider-knob-color: "var(--accent-color)"
  paper-slider-knob-start-color: "vac(--accent-color)"
  paper-slider-pin-color: "var(--accent-color)"
  paper-slider-secondary-color: "var(--secondary-background-color)"
  paper-tabs-selection-bar-color: "green"
  paper-toggle-button-checked-bar-color: "var(--accent-color)"
  paper-toggle-button-checked-button-color: "var(--accent-color)"
  paper-toggle-button-checked-ink-color: "var(--accent-color)"
  paper-toggle-button-unchecked-bar-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-button-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-ink-color: "var(--disabled-text-color)"
  primary-background-color: "#333333"
  primary-color: "#48BA92"
  primary-text-color: "#FFFFFF"
  secondary-background-color: "#333333"
  secondary-text-color: "#48BA92"
  sidebar-background-color: "var(--paper-listbox-background-color)"
  sidebar-icon-color: "rgba(255, 255, 255, 0.70)"
  sidebar-selected-icon-color: "var(--primary-color)"
  sidebar-selected-text-color: "var(--primary-text-color)"
  sidebar-text-color: "var(--primary-text-color)"
  slider-bar-color: "var(--disabled-text-color)"
  slider-color: "var(--primary-color)"
  slider-secondary-color: "var(--light-primary-color)"
  state-icon-active-color: "#47D17A"
  state-icon-color: "#44739e"
  state-icon-unavailable-color: "var(--disabled-text-color)"
  table-row-alternative-background-color: "#404040"
  table-row-background-color: "#525252"
  text-primary-color: "var(--primary-text-color)"
  toggle-button-color: "var(--primary-color)"
