---
# https://www.home-assistant.io/integrations/proximity/
evigglad:
  zone: evigglad
  devices:
    - person.allan_persson
    - person.caroline_hempel
    - person.ditte_hebsgaard
    - person.ea_hebsgaard
    - person.emil_hempel
    - person.gaester
    - person.otto
  tolerance: 50
  unit_of_measurement: km
