---
# https://companion.home-assistant.io/en/notifications/location
alias: "[Mobileapp] Request location update (Ea Hebsgaard)"
id: 37df9237-9a27-4dd9-aece-c81c649d3d42
trigger:
  - platform: time_pattern
    minutes: "/360"
action:
  - service: notify.mobile_app_eahebsgaard
    data:
      message: "request_location_update"
      data:
        tag: location
        ttl: 0
        priority: high
  - delay:
      seconds: 60
  - service: notify.mobile_app_eahebsgaard
    data:
      message: clear_notification
      data:
        tag: location
        ttl: 0
        priority: high
