---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - "home-assistant/home-assistant/releases/tag/*"
  pull_request:
  schedule:
    - cron: 0 10 * * *

jobs:
  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
  remarklint:
    name: "Remarklint"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: >
            "remark --no-stdout --color --frail
            --use preset-lint-recommended ."
  jsonlint:
    name: "Jsonlint"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Json lint
        uses: "docker://pipelinecomponents/jsonlint:latest"
        continue-on-error: true
        with:
          args: >
            "find . -not -path './.git/*' -name '*.json' -type f -print0 |
            parallel --will-cite -k -0 -n1 jsonlint -q"
  home_assistant_stable:
    name: "Home-Assistant: Stable"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: >
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./config/ --script check_config --info all
  home_assistant_beta:
    name: "Home-Assistant: Beta"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: >
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config ./config/ --script check_config --info all
  home_assistant_dev:
    name: "Home-Assistant: Developer"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: >
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: python -m homeassistant --config ./config/ --script check_config --info all
  esphome-latest:
    name: "ESPHome: Stable"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config/esphome/
      - name: esphome-latest
        uses: "docker://esphome/esphome:latest"
        continue-on-error: true
  esphome-beta:
    name: "ESPHome: Beta"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config/esphome/
      - name: esphome-beta
        uses: "docker://esphome/esphome:beta"
        continue-on-error: true
  esphome-dev:
    name: "ESPHome: Developer"
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, jsonlint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config/esphome/
      - name: esphome-dev
        uses: "docker://esphome/esphome:dev"
        continue-on-error: true
